//
// spirv.h -- aggregated declarations for the precompiled SPIR-V shader blobs
// (C arrays generated by shaders/compile.sh via glslangValidator, committed to
// the repo so builds don't need glslang - CONTRACT.md).
//
// The *_spv arrays live in src/spirv/*.c (included by vk_shaders.c, which also
// defines the *_size constants).
//

#pragma once

#include <stdint.h>
#include <stddef.h>

// textured quad (H2: graded + alpha-tested in-shader; UI path)
extern const uint32_t basic_vert_spv[];
extern const size_t basic_vert_size;

extern const uint32_t basic_frag_spv[];
extern const size_t basic_frag_size;

// textured quad with vertex-stage tint
extern const uint32_t basic_tinted_vert_spv[];
extern const size_t basic_tinted_vert_size;

// colored quad (H2: graded in-shader)
extern const uint32_t basic_color_quad_vert_spv[];
extern const size_t basic_color_quad_vert_size;

extern const uint32_t basic_color_quad_frag_spv[];
extern const size_t basic_color_quad_frag_size;

// textured model (H2: flexmodels; fog + alpha test)
extern const uint32_t model_vert_spv[];
extern const size_t model_vert_size;

extern const uint32_t model_frag_spv[];
extern const size_t model_frag_size;

// null model
extern const uint32_t nullmodel_vert_spv[];
extern const size_t nullmodel_vert_size;

// particle (textured atlas quads)
extern const uint32_t particle_vert_spv[];
extern const size_t particle_vert_size;

// particle (point list; unused by H2, kept mechanical)
extern const uint32_t point_particle_vert_spv[];
extern const size_t point_particle_vert_size;

extern const uint32_t point_particle_frag_spv[];
extern const size_t point_particle_frag_size;

// sprite model
extern const uint32_t sprite_vert_spv[];
extern const size_t sprite_vert_size;

// beam
extern const uint32_t beam_vert_spv[];
extern const size_t beam_vert_size;

// skybox
extern const uint32_t skybox_vert_spv[];
extern const size_t skybox_vert_size;

// dynamic lights
extern const uint32_t d_light_vert_spv[];
extern const size_t d_light_vert_size;

// textured, alpha blended polygon
extern const uint32_t polygon_vert_spv[];
extern const size_t polygon_vert_size;

// textured, lightmapped polygon (H2: 4 lightstyle samplers + lmScales + fog)
extern const uint32_t polygon_lmap_vert_spv[];
extern const size_t polygon_lmap_vert_size;

extern const uint32_t polygon_lmap_frag_spv[];
extern const size_t polygon_lmap_frag_size;

// warped polygon (liquids)
extern const uint32_t polygon_warp_vert_spv[];
extern const size_t polygon_warp_vert_size;

// entity shadows
extern const uint32_t shadows_vert_spv[];
extern const size_t shadows_vert_size;

// postprocess (world blit + H2 color grade)
extern const uint32_t postprocess_vert_spv[];
extern const size_t postprocess_vert_size;

extern const uint32_t postprocess_frag_spv[];
extern const size_t postprocess_frag_size;

// underwater vision warp (keyed to cl_camera_under_surface / r_underwater_warp)
extern const uint32_t world_warp_vert_spv[];
extern const size_t world_warp_vert_size;

extern const uint32_t world_warp_frag_spv[];
extern const size_t world_warp_frag_size;
