#include "compat.h"
//
// vk_shaders.c -- game shaders, compiled offline by shaders/compile.sh
// (glslangValidator -> src/spirv/*.c C arrays).
//
// Mechanical port of yquake2remaster vk_shaders.c (Copyright (C) 2018-2019
// Krzysztof Kondrak, GPLv2).
//

#include "spirv/spirv.h"

// ingame shaders stored as uint32_t arrays (autogenerated by glslangValidator)
#include "spirv/basic_vert.c"
#include "spirv/basic_tinted_vert.c"
#include "spirv/basic_frag.c"
#include "spirv/basic_color_quad_vert.c"
#include "spirv/basic_color_quad_frag.c"
#include "spirv/model_vert.c"
#include "spirv/model_frag.c"
#include "spirv/nullmodel_vert.c"
#include "spirv/particle_vert.c"
#include "spirv/point_particle_vert.c"
#include "spirv/point_particle_frag.c"
#include "spirv/sprite_vert.c"
#include "spirv/beam_vert.c"
#include "spirv/skybox_vert.c"
#include "spirv/d_light_vert.c"
#include "spirv/polygon_vert.c"
#include "spirv/polygon_lmap_vert.c"
#include "spirv/polygon_lmap_frag.c"
#include "spirv/polygon_warp_vert.c"
#include "spirv/shadows_vert.c"
#include "spirv/postprocess_vert.c"
#include "spirv/postprocess_frag.c"
#include "spirv/world_warp_vert.c"
#include "spirv/world_warp_frag.c"

const size_t basic_vert_size = sizeof(basic_vert_spv);
const size_t basic_tinted_vert_size = sizeof(basic_tinted_vert_spv);
const size_t basic_frag_size = sizeof(basic_frag_spv);

const size_t basic_color_quad_vert_size = sizeof(basic_color_quad_vert_spv);
const size_t basic_color_quad_frag_size = sizeof(basic_color_quad_frag_spv);

const size_t model_vert_size = sizeof(model_vert_spv);
const size_t model_frag_size = sizeof(model_frag_spv);

const size_t nullmodel_vert_size = sizeof(nullmodel_vert_spv);

const size_t particle_vert_size = sizeof(particle_vert_spv);

const size_t point_particle_vert_size = sizeof(point_particle_vert_spv);
const size_t point_particle_frag_size = sizeof(point_particle_frag_spv);

const size_t sprite_vert_size = sizeof(sprite_vert_spv);

const size_t beam_vert_size = sizeof(beam_vert_spv);

const size_t skybox_vert_size = sizeof(skybox_vert_spv);

const size_t d_light_vert_size = sizeof(d_light_vert_spv);

const size_t polygon_vert_size = sizeof(polygon_vert_spv);

const size_t polygon_lmap_vert_size = sizeof(polygon_lmap_vert_spv);
const size_t polygon_lmap_frag_size = sizeof(polygon_lmap_frag_spv);

const size_t polygon_warp_vert_size = sizeof(polygon_warp_vert_spv);

const size_t shadows_vert_size = sizeof(shadows_vert_spv);

const size_t postprocess_vert_size = sizeof(postprocess_vert_spv);
const size_t postprocess_frag_size = sizeof(postprocess_frag_spv);

const size_t world_warp_vert_size = sizeof(world_warp_vert_spv);
const size_t world_warp_frag_size = sizeof(world_warp_frag_spv);
